name: Test & lint all
# on:
#   push:
#     branches-ignore:
#       - master

# jobs:
#   test-lint:
#     runs-on: ubuntu-latest
#     env:
#       GPA_TOKEN: ${{ secrets.GPA_TOKEN }}
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 14
#       - run: npm ci
#       - run: npm run test
#       - run: npm run lint
